#!/bin/bash -e
if [ ! -d /tmp/build ] ; then mkdir /tmp/build; fi
svn export bgfix /tmp/build/bgfix
cd /tmp/build
find bgfix -type f -name "*.plist" -exec plutil -cbinary1 {} \;
dpkg-deb -b bgfix
rm -r /tmp/build/bgfix
dpkg-name -a bgfix.deb


