#!/bin/bash -e
if [ ! -d /tmp/build ] ; then mkdir /tmp/build; fi
svn export bgkeyboard /tmp/build/bgkeyboard
cd /tmp/build
plutil -cbinary1 bgkeyboard/System/Library/Frameworks/UIKit.framework/Keyboard-ru.plist
dpkg-deb -b bgkeyboard
rm -r /tmp/build/bgkeyboard
dpkg-name -a bgkeyboard.deb



