#!/bin/bash

case $1 in remove)

if [ -f /System/Library/Frameworks/UIKit.framework/Keyboard-ru.plist.bgkeyboard.bac ]; then 
    echo "Restoring original Keyboard-ru.plist"
    mv /System/Library/Frameworks/UIKit.framework/Keyboard-ru.plist.bgkeyboard.bac /System/Library/Frameworks/UIKit.framework/Keyboard-ru.plist
else
    echo "WARNING! Unable to restore /System/Library/Frameworks/UIKit.framework/Keyboard-ru.plist from backup. Please investigate!"
fi

if [ -d /System/Library/TextInput/TextInput_ru.bundle.bgkeyboard.bac ]; then
    echo "Restoring original TextInput_ru.bundle"
    mv /System/Library/TextInput/TextInput_ru.bundle.bgkeyboard.bac /System/Library/TextInput/TextInput_ru.bundle
else 
    echo "WARNING! Unable to restore /System/Library/TextInput/TextInput_ru.bundle from backup. Please investigate!"
fi

;;

*)

esac
